{
    'name': 'Odoo 19 HR Payroll',
    'version': '19.0.1.0.2',
    'category': 'Human Resources',
    'summary': """Odoo 19 HR Payroll, Odoo19 Payroll, Payroll, Odoo Payroll,
    Payroll V19, Odoo19, Payroll Management, Odoo19 Payslip""",
    'description': """The system automates payroll management by streamlining
     key processes such as calculating employee salaries, deductions, and 
     benefits based on predefined rules and regulations. It also facilitates
     the automatic generation of detailed payslips, ensuring accuracy in 
     payment breakdowns for each employee. This reduces manual effort, 
     minimizes errors, and ensures compliance with tax and labor laws, while
     providing employees with timely and accurate payment information""",
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.openhrms.com',
    'depends': ['hr_holidays', 'hr_timesheet_pro'],
    'data': [
        'data/ir_module_category_data.xml',
'security/hr_payroll_community_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/hr_payroll_community_data.xml',
        'data/hr_payroll_structure_india_regular.xml',
        'wizard/hr_payslips_employees_views.xml',
        'wizard/payslip_lines_contribution_register_views.xml',
        'wizard/hr_payslip_pay_wizard_views.xml',
        'report/hr_payroll_report.xml',
        'report/report_contribution_register_templates.xml',
        'report/report_payslip_templates.xml',
        'report/report_payslip_details_templates.xml',
        'views/hr_leave_type_views.xml',
        'views/hr_version_views.xml',
        'views/hr_payroll_dashboard_views.xml',
        'views/hr_salary_rule_views.xml',
        'views/hr_salary_rule_category_views.xml',
        'views/hr_contribution_register_views.xml',
        'views/hr_payroll_structure_views.xml',
        'views/hr_payslip_views.xml',
        'views/hr_payslip_line_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_payslip_run_views.xml',
        'views/res_config_settings_views.xml',
    ],
    'demo': [
        'data/hr_payroll_community_demo.xml',
        'demo/hr_payroll_community_arindam_sen_demo.xml',
    ],
    'images': ['static/description/banner.jpg'],
    'assets': {
        'web.assets_backend': [
            'hr_payroll_community/static/src/scss/payroll_theme_variables.scss',
            'hr_payroll_community/static/src/scss/payroll_theme.scss',
            'hr_payroll_community/static/src/js/backend/payroll_app_scope.js',
            'hr_payroll_community/static/src/js/dashboard/*.js',
            'hr_payroll_community/static/src/js/dashboard/*.xml',
            'hr_payroll_community/static/src/scss/dashboard.scss',
            'hr_payroll_community/static/src/js/wizard/payslip_wizard.js',
            'hr_payroll_community/static/src/js/wizard/payslip_wizard.xml',
            'hr_payroll_community/static/src/scss/payslip_wizard.scss',
        ],
    },
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
