from . import controllers
from . import ocr_controller
from . import resume_controller
from . import interview_controller
from . import attrition_controller
from . import appraisal_controller
from . import recruitment_controller
from . import task_controller
from . import esign_controller
