[options]
db_host = localhost
db_port = 5432
data_dir = /var/lib/odoo
addons_path = /opt/odoo/addons,/opt/odoo/addons/hrsd/payroll
default_productivity_apps = True
admin_passwd = $pbkdf2-sha512$600000$cy5l7P3fO6d0jnEOYWzN.Q$0dlUwqlG3K.FGdikTMJHyDv9owGltUuO3OLGf.EjTV90axTKAE4CT1swf3Et1yiWeFUnE3zMLfpthlqqVWNhLA
db_user = odoo2
db_password = odoo2

