[options]
db_host = localhost
db_port = 5432
data_dir = /Users/ibm/PS/HRSD-PP/.odoo-data
addons_path = /Users/ibm/PS/HRSD-PP/addons
default_productivity_apps = True
admin_passwd = $pbkdf2-sha512$600000$c66Vcu49B8A4B8CYc.79fw$R3pwnk7w45Lo.Gn6yKkOW//s6Mh6T7UUWI95yaB0hOyT78ElAr.vdWY2suXywkUK01h4wXeHeeFqyWZoOkqVKg
db_user = odoo2
db_password = odoo2
wkhtmltopdf_path = /usr/local/bin/wkhtmltopdf-rosetta
