[options]
db_host = localhost
db_port = 5432
addons_path = /Users/amit/PS2/odoo/addons,/Users/amit/PS2/odoo/addons/hrsd/payroll
default_productivity_apps = True
admin_passwd = $pbkdf2-sha512$600000$cy5l7P3fO6d0jnEOYWzN.Q$0dlUwqlG3K.FGdikTMJHyDv9owGltUuO3OLGf.EjTV90axTKAE4CT1swf3Et1yiWeFUnE3zMLfpthlqqVWNhLA
db_user = odoo2
db_password = odoo2

