{
    'name': 'HRSD',
    'version': '1.0',
    'category': 'Human Resources',
    'summary': 'HR Service Delivery',
    'description': 'HR Service Delivery Application',
    'author': 'My Company',
    'website': 'https://www.yourcompany.com',
    'depends': [
        'base',
        'mail',
        'hr',
        'hr_expense',
        'hr_holidays',
        'hr_recruitment',
        'hr_attendance',
        'fleet',
        'hr_skills',
        'lunch',
        'hr_work_entry',
        'hr_timesheet',
        'website_hr_recruitment',
        'hr_timesheet_attendance',
        'hr_hourly_cost',
        'hr_maintenance',
        'website_hr_recruitment_livechat',
        'hr_recruitment_survey',
        'document_templates',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/hr_recruitment_sequence.xml',
        'data/hr_recruitment_mail_alias.xml',
        'data/hr_task_timesheet_sequence.xml',
        'data/hr_esign_data.xml',
        'views/views.xml',
        'views/hrsd_dashboard_menu_views.xml',
        'data/hrsd_dashboard_menu_data.xml',
        'views/hrsd_dashboard_navbar_views.xml',
        'data/hrsd_dashboard_navbar_data.xml',
        'views/hrsd_dashboard_stat_card_views.xml',
        'data/hrsd_dashboard_stat_card_data.xml',
        'views/templates.xml',
        'views/templates_ocr.xml',
        'views/hr_document_ocr_views.xml',
        'views/templates_resume.xml',
        'views/hr_resume_views.xml',
        'views/templates_interview.xml',
        'views/templates_attrition.xml',
        'views/hr_appraisal_views.xml',
        'views/templates_appraisal.xml',
        'views/login_templates.xml',
        'views/templates_recruitment.xml',
        'views/templates_recruitment_requirements.xml',
        'views/hr_recruitment_views.xml',
        'views/hr_timesheet_entry_views.xml',
        'views/templates_tasks.xml',
        'views/hr_esign_views.xml',
        'views/hr_esign_portal_templates.xml',
    ],
    'demo': [
        'demo/demo.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'hrsd/static/src/scss/hrsd_backend_variables.scss',
            'hrsd/static/src/scss/hrsd_backend_theme.scss',
            'hrsd/static/src/scss/hrsd_back_button.scss',
            'hrsd/static/src/js/backend/control_panel_back_button.js',
            'hrsd/static/src/js/backend/backend_cleanup.js',
            'hrsd/static/src/xml/control_panel_back_button.xml',
            'hrsd/static/src/hr_esign/**/*.scss',
            'hrsd/static/src/hr_esign/**/*.js',
            'hrsd/static/src/hr_esign/**/*.xml',
        ],
    },
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
}
