from . import models
from . import hrsd_dashboard
from . import hrsd_dashboard_menu
from . import hrsd_dashboard_navbar
from . import hrsd_dashboard_stat_card
from . import hrsd_dashboard_widget
from . import hr_document_ocr
from . import hr_resume_screening
from . import hr_interview
from . import hr_attrition
from . import hr_attrition_assessment
from . import hr_appraisal
from . import hr_appraisal_lines
from . import hr_recruitment
from . import hr_recruitment_candidate
from . import hr_recruitment_note
from . import hr_esign
from . import hr_timesheet_entry
from . import hr_task
